version: '3.4'

services:
  devenv:
    image: devenv
    build:
      context: .
      dockerfile: ./Dockerfile
      args:  # Pass build-time variables
        DOCKER_BUILDKIT: 1
      ssh:
        - default
    environment:  # Runtime environment variables
      DISPLAY: :0

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
